source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
use_frameworks!
workspace './PagingMenuControllerDemo.xcworkspace'

target 'PagingMenuControllerDemo' do
  pod "PagingMenuController", :path => "../"
end

target 'PagingMenuControllerDemo2' do
  pod "PagingMenuController", :path => "../"
end

target 'PagingMenuControllerDemoTests' do
  pod "PagingMenuController", :path => "../"
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
     config.build_settings['SWIFT_VERSION'] = '5.0'
   end
 end
end
